mkdir ~/.config/alacritty >/dev/null 2>&1
cp -r alacritty ~/.config
mkdir ~/.config/labwc >/dev/null 2>&1
cp -r labwc ~/.config
mkdir ~/.config/sfwbar >/dev/null 2>&1
cp -r sfwbar ~/.config
mkdir ~/.themes 2> /dev/null
cp -r Nightmare-01 ~/.themes
cp -r Nightmare-02 ~/.themes
cp -r Nightmare-03 ~/.themes
mkdir ~/.config/kanshi >/dev/null 2>&1
cp -r kanshi ~/.config
mkdir ~/scripts >/dev/null 2>&1
cp -r scripts ~/
mkdir ~/.config/rofi >/dev/null 2>&1
cp -r rofi ~/.config
mkdir ~/.config/labwc-themes >/dev/null 2>&1
cp -r labwc-themes ~/.config
cp .labwc ~/
